// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgService.proto

package np.com.narayan.thapa.services;

public final class MessageRpc {
  private MessageRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020msgService.proto\022%np.com.thapanarayan." +
      "entities.services\032\016messages.proto2}\n\016Mes" +
      "sageService\022k\n\004chat\022..np.com.thapanaraya" +
      "n.entities.pb.MessageInFlow\032/.np.com.tha" +
      "panarayan.entities.pb.MessageOutFlow(\0010\001" +
      "B.\n\035np.com.narayan.thapa.servicesB\nMessa" +
      "geRpc\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          np.com.narayan.thapa.dtos.MessageProto.getDescriptor(),
        });
    np.com.narayan.thapa.dtos.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
